language: node_js
node_js: "lts/*"
cache: yarn
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  firefox: 'latest'
  apt:
    sources:
      - ubuntu-toolchain-r-test
stages:
  - build
  - test
  - docs
  - deploy
script: skip
jobs:
  include:
  - stage: build
    name: "Build"
    script: yarn build
  - stage: test
    name: "Browser"
    script: yarn test:browser
  - script: yarn test:node
    name: "Node.js"
  - script: yarn test:webworker
    name: "Service Worker"
  - stage: docs
    name: "Coverage"
    script: yarn coverage-publish
  - script: yarn docs
    name: "API Docs"
  - stage: deploy
    script: skip
    deploy:
      - provider: releases
        api_key: $GITHUB_TOKEN
        file:
        - dist/index.js
        - dist/index.min.js
        skip_cleanup: true
        on:
          branch: release
          tags: true
      - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: docs
        target-branch: gh-pages
        on:
          branch: release
          tags: true
      - provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          branch: release
          tags: true
